// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkgdcpzsmfnwuqvifhfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZ2RjcHpzbWZud3VxdmlmaGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDgwNjksImV4cCI6MjA2ODUyNDA2OX0.BeI0CnbeUnj6ijqEsP4_nGnK035aTUyAzM7BFmJLX9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});